language: scala
scala:
  - 2.12.4

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

jdk:
  - oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  email: false
  slack: iosr201718-bgrz:AuPSpSRW4zE4xa5nTSB0tNAK
